config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
  	resources :relationships
  end

  root 'homes#top'

  resources :nails do
  	resource :favorites, only:[:create, :destroy]
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :nail
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  # GET /comments
  # GET /comments.json
  def index
    @comments = Comment.all
    @nail = Nail.find(params[:nail_id])
    now = Time.current
    nail_ranking = Comment.where(created_at: Time.now.all_month).group(:nail_id).order("avg(comments.rate) desc").limit(3).pluck("nail_id,avg(comments.rate)")
      @nail_ranking = nail_ranking.map do |r|
        {
          nail:Nail.find(r[0]),
          average:r[1]
        }
      end
  end

  # GET /comments/1
  # GET /comments/1.json
  def show
  end

  # GET /comments/new
  def new
    @nail = Nail.find(params[:nail_id])
    @comment = Comment.new
    @comment.user_id = current_user.id
    @comment.nail_id = @nail.id

  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  # POST /comments.json
  def create
    @nail = Nail.find(params[:nail_id])
    @comment = Comment.new(comment_params)
    @comment.user_id = current_user.id
    @comment.nail_id = @nail.id

    respond_to do |format|
      if @comment.save
        format.html { redirect_to nail_comments_path, notice: 'Comment was successfully created.' }
        format.json { render :show, status: :created, location: @comment }
      else
        format.html { render :new }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comments/1
  # PATCH/PUT /comments/1.json
  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to @comment, notice: 'Comment was successfully updated.' }
        format.json { render :show, status: :ok, location: @comment }
      else
        format.html { render :edit }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to comments_url, notice: 'Comment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def comment_params
      params.permit(:user_id, :nail_id, :rate, :title, :content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_edit.form.html.erb
<%= form_with model: comment, url: edit_nail_comment_path(comment),local: true do |form| %>
  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :nail_id %>
    <%= form.number_field :nail_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [comment,nail] , url: nail_comments_path, method: :post, local: true do |form| %>

  <% if comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
      <% comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <!--nailコードの送信-->
  <%= form.hidden_field :nail_id %>
  <%= form.hidden_field :comment %>
  <div class="form-group row">
        <%= form.label :nail_name, '商品名 ', class:'col-md-3 col-form-label' %>
        <div class="col-md-9">
          <%= form.text_field :nail_name, class: "form-control" %>
        </div>
      </div>

      <!-- タイトル -->
      <div class="form-group row">
        <%= form.label :title, 'タイトル ', class:'col-md-3 col-form-label' %>
        <div class="col-md-9">
          <%= form.text_field :title, class: "form-control" %>
        </div>
      </div>

      <!-- 評価 -->
      <div class="form-group row" id="star">
        <%= form.label :rate,'評価 ', class:'col-md-3 col-form-label' %>
        <%= form.hidden_field :rate, id: :review_star %>
      </div>

      <!-- 評価javascript -->
      <script>
      $('#star').raty({
        size     : 36,
        starOff:  '<%= asset_path('star-off.png') %>',
        starOn : '<%= asset_path('star-on.png') %>',
        starHalf: '<%= asset_path('star-half.png') %>',
        scoreName: 'post[rate]',
        half: true,
      });
      </script>

      <!-- 口コミ -->
      <div class="form-group row">
        <%= form.label :content, '口コミ内容 ', class:'col-md-3 col-form-label' %>
        <div class="col-md-9">
          <%= form.text_area :content, class: "form-control", rows: "8",
            placeholder:'口コミ内容がなくても、タイトルと評価のみで投稿できます。
    まずは投稿してみましょう！投稿してから編集もできますよ！' %>
        </div>
      </div>

      <!-- 確認ボタン -->
      <div class="form-group row justify-content-end">
        <div class="col-md-9">
          <%= form.submit '投稿する', class:"btn btn-success" %>
        </div>
      </div>
    <!-- /口コミ入力フォーム -->
  <% end %>

app/views/comments/edit.html.erb
<div class="container">
	<h1>Editing Comment</h1>

	<%= render 'edit.form', comment: @comment %>

	<%= link_to 'Show', nail_comment_path(@comment) %> |
	<%= link_to 'Back', nail_comments_path %>
</div>

app/views/comments/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>

  <h1>Comments</h1>

  <table>
    <thead>
      <tr>
        <th>User ID</th>
        <td></td>
        <th>Nail ID</th>
        <td></td>
        <th>評価</th>
        <td></td>
        <th>コメント</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @comments.each do |comment| %>
        <tr>
          <td><%= comment.user_id %></td>
          <td></td>
          <td><%= comment.nail_id %></td>
          <td></td>
          <td><%= comment.rate %></td>
          <td></td>
          <td><%= comment.content %></td>
          <td></td>
          <td><%= link_to 'Show', nail_comment_path(comment.id,comment.nail.id) %></td>
          <td><%= link_to 'Edit', edit_nail_comment_path(comment.id,comment.nail.id) %></td>
          <td><%= link_to 'Destroy', nail_comment_path(comment.id, comment.nail.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

<%= link_to 'New Comment', new_nail_comment_path %>
</div>

app/views/comments/new.html.erb
<div class="container">
<h1>New Comment</h1>

<%= render 'form', comment: @comment, nail: @nail %>

<%= link_to 'Back', nail_comments_path,class:"btn btn-success" %>
</div>

app/views/comments/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<p>
  <strong>Nail:</strong>
  <%= @comment.nail_id %>
</p>

<%= link_to 'Edit', edit_nail_comment_path(@comment) %> |
<%= link_to 'Back', nail_comments_path %>
</div>