config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users do
  	resources :relationships
  end

  root 'homes#top'

  resources :nails do
  	resource :favorites, only:[:create, :destroy]
  	resources :comments
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :nails, dependent: :destroy
  has_many :favorites
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def index
		@user = current_user
		@favorites = Favorite.all
		@nails = Nail.where(user_id: @user.id)
	end

	def edit
		@user = User.find(params[:id])
	end

	private
	def user_params
  		params.require(:user).permit(:last_name, :first_name,:last_name_kana, :first_name_kana, :address, :telephone_number, :email)
  	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="container">
	<h2>登録情報を編集する</h2>
	<%= form_with model: @user, local: true ,url: edit_user_path(@user), html: { method: :put } do |f| %>
	 <table>
	    <tr>
	      <div class="field">
	        <th><%= f.label :名前 %></th>
	        <td>(姓)</td>
	        <td><%= f.text_field :last_name, autofocus: true, autocomplete: "last_name" %></td>
	        <td>(名)</td>
	        <td><%= f.text_field :first_name, autofocus: true, autocomplete: "first_name" %></td>
	      </div>
	    </tr>

	    <tr>
	      <div class="field">
	        <th><%= f.label :フリガナ %></th>
	        <td>(セイ)</td>
	        <td><%= f.text_field :last_name_kana, autofocus: true, autocomplete: "last_name_kana" %></td>
	        <td>(メイ)</td>
	        <td><%= f.text_field :first_name_kana, autofocus: true, autocomplete: "first_name_kana" %></td>
	      </div>
	    </tr>

	    <tr>
	      <div class="field">
	        <th><%= f.label :メールアドレス %></th>
	        <td></td>
	        <td><%= f.email_field :email, autofocus: true, autocomplete: "email" %></td>
	        <td></td>
	        <td></td>
	      </div>
	    </tr>

	    <tr>
	      <div class="field">
	        <th><%= f.label :住所 %></th>
	        <td></td>
	        <td colspan="3"><%= f.text_field :address, autofocus: true, autocomplete: "address" %></td>
	        <td></td>
	        <td></td>
	      </div>
	    </tr>

	    <tr>
	      <div class="field">
	        <th><%= f.label :電話番号 %></th>
	        <td></td>
	        <td><%= f.text_field :telephone_number, autofocus: true, autocomplete: "telephone_number" %></td>
	        <td></td>
	        <td></td>
	      </div>
	    </tr>
	    <tr>
	    <div class="field">
	    	<td><%= f.submit "更新する" %></td>
	    	<td></td>
	    	<td></td>
	    </div>
		</tr>
    </table>

	<% end %>
</div>

app/views/users/index.html.erb
<div class="container">

<div class="row">
    <h2>登録情報</h2>
  </div>

  <div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-3"></div>
    <div class="col-lg-2"></div>
    <div class="col-lg-2"></div>
    <div class="col-lg-1"></div>
    <div class="col-lg-2"></div>
  </div>

  <div id="reg" class="row">
    <table class="table">
      <thead class="thead-light">
        <tr>
          <th>登録氏名</th>
          <th>登録住所</th>
          <th>電話番号</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <th><%= current_user.last_name + current_user.first_name %></th>
          <th><%= @user.address %></th>
          <th><%= @user.telephone_number %></th>
          <th></th>
          <th><%= link_to "登録情報を編集する", edit_user_path(current_user) %></th>
      </tr>
      </tbody>
    </table>
  </div>
  <h4>投稿した商品</h4>
  <div class="row">
    <% @nails.each do |nail| %>
    <div class="post">
      <div><%= attachment_image_tag nail, :image,:fill, 100, 100, format: "jpeg" %></div>
      <div><%= link_to nail.name, nail_path(nail) %></div>
      <div><%= nail.price %>円</div>
    </div>
    <% end %>
  </div>
  <h4>お気に入り商品</h4>
    <div id="favorite-box" class="row">
      <% @favorites.each do |favorite| %>
        <div id="favorite">
          <%= attachment_image_tag favorite.nail, :image,:fill, 100, 100, format: "jpeg" %>
          <div><%= link_to favorite.nail.name, users_nail_path(favorite.nail) %></div>
          <div><%= favorite.item.price %>円</div>
        </div>
      <% end %>
    </div>
</div>